# Shiny App for Resazurin Trial Data Exploration
# Author: Auto-generated by GitHub Copilot assistant
# Purpose: Interactive loading, normalization, blank correction, and plotting of resazurin plate reader data.

library(shiny)
library(shinythemes)
library(readxl)
library(tidyverse)
library(tools)
library(DT)
library(plotly)
library(pracma)
library(stringr)

#-----------------------------
# Helper functions
#-----------------------------

read_plate_file <- function(file_path){
  file_name <- file_path_sans_ext(basename(file_path))
  dat <- read_excel(file_path, skip = 10, col_names = FALSE)
  # Keep first 4 rows (matching analysis script) NOTE: update if full 8 rows are desired
  dat <- dat[1:4, ]
  colnames(dat) <- c("Row", as.character(1:13))
  dat_long <- dat %>%
    pivot_longer(-Row, names_to = "Column", values_to = "Value") %>%
    mutate(
      Column = sprintf("%02d", as.integer(Column)),
      well = paste0(Row, Column),
  plate = str_extract(file_name, "plate\\d+"),
  date = str_extract(file_name, "^\\d{8}"),
  timepoint = str_extract(file_name, "T\\d+") %>% str_remove("T") %>% as.numeric()
    ) %>%
    select(date, plate, well, timepoint, resazurin_counts = Value, file_name)
  dat_long
}

process_uploaded_files <- function(file_inputs){
  validate(need(nrow(file_inputs) > 0, "Upload at least one plate file"))
  paths <- file_inputs$datapath
  out_list <- lapply(paths, read_plate_file)
  bind_rows(out_list)
}

merge_with_metadata <- function(plate_df, metadata_df){
  plate_df %>% left_join(metadata_df, by = c("date","plate","well")) %>% filter(!is.na(type))
}

merge_with_size <- function(df, size_df){
  df %>% left_join(size_df, by = c("date","plate","well"))
}

normalize_and_blank_correct <- function(df){
  df <- df %>% group_by(date, plate, well, family) %>% arrange(timepoint) %>%
    mutate(fluorescence.norm = resazurin_counts/first(resazurin_counts)) %>% ungroup()
  blanks <- df %>% filter(type == "blank") %>% group_by(date, plate, timepoint) %>%
    summarise(mean_blank = mean(fluorescence.norm), .groups = "drop")
  df2 <- df %>% left_join(blanks, by = c("date","plate","timepoint")) %>%
    filter(type != "blank") %>%
    mutate(fluorescence.corr = fluorescence.norm - mean_blank,
           value = fluorescence.corr/length.mm,
           unique = paste(date, plate, well))
  df2
}

filter_oversaturated <- function(df, threshold = 3000){
  oversat_ids <- df %>% filter(resazurin_counts > threshold) %>%
    mutate(unique = paste(date, plate, well)) %>% distinct(unique) %>% pull(unique)
  df %>% filter(!unique %in% oversat_ids)
}

compute_auc <- function(df){
  df %>% mutate(time = as.numeric(timepoint)) %>% 
    group_by(date, plate, well, family, phenotype) %>%
    summarise(AUC = trapz(time, value), .groups = "drop")
}

compute_deltas <- function(df){
  wide <- df %>% select(date, plate, well, family, phenotype, timepoint, value) %>%
    pivot_wider(names_from = timepoint, values_from = value)
  if(!all(c("0","1","2","3","4") %in% names(wide))) return(tibble())
  wide %>% mutate(
    delta_T0_T1 = (`1`-`0`),
    delta_T1_T2 = (`2`-`1`)/`1`,
    delta_T2_T3 = (`3`-`2`)/`2`,
    delta_T3_T4 = (`4`-`3`)/`3`
  )
}

#-----------------------------
# UI
#-----------------------------

tu <- tagList(
  theme = shinytheme("flatly"),
  navbarPage(
    title = "Resazurin Trials Explorer",
    tabPanel("Upload & Data",
             sidebarLayout(
               sidebarPanel(width = 3,
                            fileInput("plate_files", "Plate Reader Files (.xlsx)", multiple = TRUE, accept = c('.xlsx')),
                            fileInput("metadata_file", "Metadata File", accept = c('.xlsx')),
                            fileInput("size_file", "Size File", accept = c('.xlsx')),
                            checkboxInput("exclude_20250630", "Exclude 20250630", TRUE),
                            numericInput("oversat", "Oversaturation Threshold", 3000, min = 1000, step = 100),
                            actionButton("process", "Process Data", class = "btn-primary")
               ),
               mainPanel(
                 tabsetPanel(
                   tabPanel("Preview", DTOutput("raw_preview")),
                   tabPanel("Processed", DTOutput("processed_preview")),
                   tabPanel("AUC", DTOutput("auc_table")),
                   tabPanel("Deltas", DTOutput("deltas_table"))
                 )
               )
             )
    ),
    tabPanel("Trajectories",
             sidebarLayout(
               sidebarPanel(width = 3,
                            selectInput("color_by", "Color By", choices = c("family","phenotype","temperature","length.mm"), selected = "family"),
                            selectInput("facet_by", "Facet By", choices = c(None = ".","date","family","phenotype"), selected = "date"),
                            sliderInput("time_range", "Timepoints", min = 0, max = 4, value = c(0,4), step = 1),
                            checkboxInput("show_points", "Show Points", TRUE),
                            checkboxInput("show_lines", "Show Lines", TRUE),
                            checkboxInput("use_loess", "Smooth (loess)", FALSE),
                            checkboxInput("log_y", "Log10 Y", FALSE)
               ),
               mainPanel(
                 plotlyOutput("trajectory_plot", height = 600)
               )
             )
    ),
    tabPanel("Summaries",
             sidebarLayout(
               sidebarPanel(width = 3,
                            selectInput("summary_metric", "Metric", choices = c("AUC","delta_T0_T1","delta_T1_T2","delta_T2_T3","delta_T3_T4")),
                            selectInput("group_var", "Group", choices = c("family","phenotype"), selected = "family"),
                            checkboxInput("jitter", "Add Jitter", TRUE)
               ),
               mainPanel(
                 plotlyOutput("summary_plot", height = 600)
               )
             )
    )
  )
)

#-----------------------------
# SERVER
#-----------------------------

sv <- function(input, output, session){
  raw_data <- eventReactive(input$process, {
    req(input$plate_files)
    df <- process_uploaded_files(input$plate_files)
    if(input$exclude_20250630){
      df <- df %>% filter(date != '20250630')
    }
    df
  })

  metadata <- reactive({
    req(input$metadata_file)
    read_excel(input$metadata_file$datapath) %>% mutate(date = as.character(date))
  })

  size_df <- reactive({
    req(input$size_file)
    read_excel(input$size_file$datapath) %>% mutate(date = as.character(date))
  })

  processed <- reactive({
    req(raw_data(), metadata(), size_df())
    md <- metadata()
    sd <- size_df()
    merged <- raw_data() %>% mutate(date = as.character(date)) %>% merge_with_metadata(md) %>% merge_with_size(sd)
    norm <- normalize_and_blank_correct(merged)
    filtered <- filter_oversaturated(norm, threshold = input$oversat)
    filtered
  })

  aucs <- reactive({
    req(processed())
    compute_auc(processed())
  })

  deltas <- reactive({
    req(processed())
    compute_deltas(processed())
  })

  output$raw_preview <- renderDT({
    datatable(raw_data(), options = list(pageLength = 5, scrollX = TRUE))
  })

  output$processed_preview <- renderDT({
    datatable(processed(), options = list(pageLength = 10, scrollX = TRUE))
  })

  output$auc_table <- renderDT({
    datatable(aucs(), options = list(pageLength = 10, scrollX = TRUE))
  })

  output$deltas_table <- renderDT({
    datatable(deltas(), options = list(pageLength = 10, scrollX = TRUE))
  })

  output$trajectory_plot <- renderPlotly({
    df <- processed()
    req(nrow(df) > 0)
    df <- df %>% filter(timepoint >= input$time_range[1], timepoint <= input$time_range[2])
    p <- ggplot(df, aes(x = timepoint, y = value, group = unique))
    color_var <- sym(input$color_by)
    if(input$color_by == 'length.mm'){
      p <- p + geom_point(aes(color = !!color_var), size = 1, alpha = 0.7)
    } else if(input$show_points){
      p <- p + geom_point(aes(color = !!color_var), size = 1, alpha = 0.6)
    }
    if(input$show_lines){
      p <- p + geom_line(aes(color = !!color_var), alpha = 0.4)
    }
    if(input$use_loess){
      p <- p + stat_smooth(aes(color = !!color_var, group = !!color_var), method = 'loess', se = FALSE, linewidth = 1.1)
    }
    if(input$facet_by != '.'){
      facet_var <- as.formula(paste('~', input$facet_by))
      p <- p + facet_wrap(facet_var, scales = 'free_y')
    }
    if(input$log_y){
      p <- p + scale_y_log10()
    }
    p <- p + theme_classic() + labs(x = 'Timepoint', y = 'Normalized Fluorescence (corr/mm)', color = input$color_by)
    ggplotly(p)
  })

  output$summary_plot <- renderPlotly({
    metric <- input$summary_metric
    grp <- input$group_var
    if(metric == 'AUC'){
      dat <- aucs()
      yvar <- 'AUC'
    } else {
      dat <- deltas()
      yvar <- metric
    }
    req(nrow(dat) > 0)
    p <- ggplot(dat, aes_string(x = grp, y = yvar, color = grp)) +
      geom_violin(fill = NA) +
      {if(input$jitter) geom_jitter(width = 0.15, alpha = 0.5)} +
      theme_classic() + labs(x = grp, y = yvar)
    ggplotly(p)
  })
}

shinyApp(ui = tu, server = sv)
